server:
  port: 5701
logging:
  file:
    path: logs

spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev

esctasy:
  qqchat:
    ws:
      retry:
        enable: true
        max: 5
        interval: 3000
      socket-path: ws://localhost:5700
    third-chat:
      model: xx
      qingyun:
        api: xxx
      bard:
        token: xxxs
